const router = require('express').Router()
const Card = require('../models/employeeCard')
const User = require('../models/user')

// create employee card
router.post('/create-card', async (req, res) => {
  try {
    // get data and save it
    const { name, role, email, department } = req.body
    const { id } = req.headers

    // Check if the User exists
    const user = await User.findById(id)
    if (!user) {
      return res.status(404).json({ message: 'User not found!' })
    }

    // Create and save new card
    const newCard = new Card({
      name: name,
      role: role,
      email: email,
      department: department
    })

    const saveCard = await newCard.save()

    // update user's card-Array with the new card Id (id comes from the default id generated by mongodb)
    const cardId = saveCard._id
    await User.findByIdAndUpdate(
      id,
      { $push: { cards: cardId._id } },
      { new: true }
    )

    // response
    res.status(201).json({
      message: 'Employee card created successfully 🎉',
      card: saveCard
    })
  } catch (error) {
    // Handle duplicate key error
    if (error.code === 11000) {
      return res.status(400).json({
        message: `Duplicate key error: ${
          Object.keys(error.keyValue)[0]
        } must be unique.`,
        field: error.keyValue
      })
    }
    console.log(error)
    res.status(500).json({ message: 'Internal Server Error' })
  }
})

module.exports = router
